# Dockerfile
FROM mysql:8.0.15

ENV MYSQL_DATABASE=spring_framework \
	MYSQL_USER=root \
    MYSQL_ROOT_PASSWORD=root

#COPY my-sql/initialize-db.sql/ /docker-entrypoint-initdb.d/ if you want to add some intialize sql script

EXPOSE 3306